### ISSUE TITLE
Relative Attention in Point branch?

### ISSUE THREAD

**Issue by shanjiayao** [HaochengWan/PVT#1]
Hi, it's really a nice work, but I have some problems about point branch.

As described in paper, the **Relative Attention** is performed in the point branch to obtains significant improvements over not using this RPR term without adding extra training parameters. But it seems that there is not relative code in repo?

https://github.com/HaochengWan/PVT/blob/master/modules/pvtconv.py#L298

**Comment by shanjiayao** [comment]
@HaochengWan

**Comment by zhangcheng828** [comment]
Hi, we will release our code about the latest version in two weeks.

**Comment by zhangcheng828** [comment]
Hi, the code of Relative Attention was uploaded.

**Comment by shanjiayao** [comment]
> Hi, the code of Relative Attention was uploaded.

Thanks for your reply, it's really helpful!
